name: Deploy Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Frontend to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "./frontend" # Path to your frontend folder

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend # Make sure frontend deploys first
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0" # Specify your Node.js version

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Deploy Backend (Example to Heroku)
        run: |
          git remote add heroku https://git.heroku.com/your-app-name.git
          git push heroku main  # Push to your Heroku app
